# Generated by Django 4.2.2 on 2023-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_purchases_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delievered',
            field=models.BooleanField(default=False),
        ),
    ]
