# Generated by Django 4.2.2 on 2023-07-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_ispaid_order_order_date_order_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delievered',
        ),
    ]
