# Generated by Django 4.2.2 on 2023-06-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
