# Generated by Django 4.2.2 on 2023-06-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='zara', on_delete=django.db.models.deletion.CASCADE, to='products.brand', to_field='name'),
            preserve_default=False,
        ),
    ]
