# Generated by Django 4.2.2 on 2023-06-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='gender',
        ),
    ]
