# Generated by Django 4.2.2 on 2023-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_category_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MEN', 'men'), ('WOMEN', 'women'), ('BOYS', 'boys'), ('GIRLS', 'girls'), ('UNISEX', 'unisex')], max_length=100),
        ),
    ]
