# Generated by Django 4.2.2 on 2023-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jeans', 'jeans'), ('shirts', 'shirts'), ('t-shirts', 't-shirts'), ('shorts', 'shorts'), ('trousers', 'trousers'), ('shoes', 'shoes'), ('traditionals', 'traditionals'), ('sarees', 'sarees'), ('accessories', 'accessories')], default='accessories', max_length=100),
            preserve_default=False,
        ),
    ]
